version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  app:
    container_name: app
    restart: always
    image: ssi-api-pkd:1.0
    ports:
      - '8080:8080'
    environment:
      MONGODB_URL: "mongodb://mongo:27017/ssi-api"
      ACCOUNT_ADDRESS: ""
      ACCOUNT_PRIVATE_ENCRYPTION_KEY: ""
      ACCOUNT_PRIVATE_KEY: ""
      ACCOUNT_PUBLIC_ENCRYPTION_KEY: ""
      NETWORK_RPC: ""
      NODE_ADDRESS: ""
      NODE_EXPIRATION: 
    command: >
      sh -c "npm start"
    links:
      - mongo
